apiVersion: v1
metadata:
  namespace: clearml
spec:
  containers:
  - resources:
      limits:
        cpu:             1000m
        memory:          4G
      requests:
        cpu:             1000m
        memory:          4G
  restartPolicy: Never
